### PR TITLE
Fix handling of incoming cookies, and add unit test

### PR DESCRIPTION
**Pull request by mjholgate**
This unit test currently fails, but I think it should pass...

See issue #110.

### CODE REVIEW

**Comment by mjholgate** [comment]
I've added a commit to fix the bug, and the unit tests now pass.

**Comment by mjholgate** [comment]
Hiya, is Nocilla still active? If not, I'll close this PR.

**Comment by luisobo** [comment]
Yes, it is. I can't devote as much time as I'd like tho.

Thanks for the contribution!

**Comment by mjholgate** [comment]
Thanks @luisobo!

**Pull request merged**
